#! /usr/bin/env bash

pip install --user virtualenv
mkdir venv
python -m virtualenv venv
source venv/bin/activate

pip install nltk
python nltk_download.py

pip install scipy
pip install -U scikit-learn
pip install numpy



export CLASSPATH=/home/khatwani/Desktop/NLP_Project/stanford-ner-2017-06-09/stanford-ner.jar:/home/khatwani/Desktop/NLP_Project/stanford-parser-full-2017-06-09/stanford-parser.jar:/home/khatwani/Desktop/NLP_Project/stanford-postagger-2017-06-09/stanford-postagger.jar

export STANFORD_MODELS=/home/khatwani/Desktop/NLP_Project/stanford-ner-2017-06-09/classifiers/english.all.3class.distsim.crf.ser.gz:/home/khatwani/Desktop/NLP_Project/stanford-postagger-2017-06-09/models/english.conll.4class.distsim.crf.ser.gz:/home/khatwani/Desktop/NLP_Project/stanford-ner-2017-06-09/english.muc.7class.distsim.crf.ser.gz

python nlpProject.py $1 > $1".templates"






